/* tslint:disable */
/* eslint-disable */
/**
 * This file was automatically generated by Payload.
 * DO NOT MODIFY IT BY HAND. Instead, modify your source Payload config,
 * and re-run `payload generate:types` to regenerate this file.
 */

export interface Config {
  collections: {
    media: Media;
    deals: Deal;
    users: User;
    'payload-preferences': PayloadPreference;
    'payload-migrations': PayloadMigration;
  };
  globals: {};
}
export interface Media {
  id: string;
  alt: string;
  updatedAt: string;
  createdAt: string;
  url?: string | null;
  filename?: string | null;
  mimeType?: string | null;
  filesize?: number | null;
  width?: number | null;
  height?: number | null;
}
export interface Deal {
  id: string;
  active?: boolean | null;
  title: string;
  description: string;
  brand: (
    | '1LYFE'
    | 'ABX'
    | 'AE EL BLUNTO'
    | 'AKWAABA FARMS'
    | 'ALIEN APE'
    | 'ARTISANAL HEMP'
    | 'ASH and EMBER'
    | 'ASH and EMBER'
    | 'B.O.B STASH'
    | 'B.O.B. STASH'
    | 'BABY JEETER'
    | 'BABY JETTER'
    | 'BAGGIE BUDS'
    | "BALIEY'S"
    | 'BALL FAMILY FARMS'
    | 'BANGERS'
    | 'BELEAF'
    | 'BEMORE'
    | 'BHANG'
    | 'BIC'
    | 'BIG BOY DRO'
    | 'BIG BOY DRO'
    | "BIG PETE'S"
    | 'BIIGO'
    | 'BOB'
    | 'BOLT'
    | 'BOTANIC TONICS'
    | 'BRIZA BOTANICALS'
    | 'BUGLER'
    | 'BULK'
    | 'BUZZED'
    | 'CALI BORN DREAMS'
    | 'CALI CLOUDX'
    | 'CALI- BORN- DREAMS'
    | 'CALI-BORN DREAMS'
    | 'CAMINO'
    | 'CANNATRUST'
    | 'CANNATRUT'
    | 'CANNNATRUST'
    | 'CARE BY DESIGN'
    | 'CHEEBA CHEW'
    | 'CHERRYWORLD'
    | 'CLEAN AF'
    | 'CLEANAF'
    | 'CLIPPER'
    | 'CLSICS'
    | 'DABSTRACT'
    | 'DAZZLEAF'
    | 'DESSERT UNDERGROUND'
    | 'DILLS'
    | 'DO NOT USE'
    | 'DOLLAR DOSE'
    | 'DOMEPEN'
    | 'DOMEPN'
    | 'DOMPEN'
    | 'DROPS'
    | 'EAGLE'
    | 'EIGHTY EAST'
    | 'EIGHTY EAST'
    | 'ELEMENT'
    | 'ELEMENTS'
    | 'ELYON'
    | 'EMBER VALLEY'
    | 'EMERALD BAY EXTRACTS'
    | 'EMERALD BAY EXTRACTS'
    | 'EMERALD SKY'
    | 'EMERLAD BAY EXTRACTS'
    | 'EMPIRE WELLNESS'
    | 'EQUILIBRIUM'
    | 'EQUILIBRIUM GENETICS'
    | 'EVERDAY DABS'
    | 'EVERY DAY'
    | 'EVERY DAY DAB'
    | 'EVERY DAY DABS'
    | 'EVERYDAY DABS'
    | 'EVERYDAY SLUGGER'
    | 'EXTRAX'
    | 'FARMER AND THE FELON'
    | 'FEELZ'
    | 'FIG FARMS'
    | 'FLAV'
    | 'FLAWLESS'
    | 'FLAWLESS FLOWER'
    | 'FLAWLESS FLOWERS'
    | 'FLORACAL'
    | 'FLORCAL'
    | 'FLOS'
    | 'FORMULA 420'
    | 'FROSTED FLOWERS'
    | 'FUZED'
    | 'GANJA GOLD'
    | 'GEALTO'
    | 'GELATO'
    | 'GENERIC...'
    | 'GLAS HOUSE FARMS'
    | 'GLASHOUSE'
    | 'GLASS HOUSE FARMS'
    | 'GLASS HOUSE FARMS'
    | 'GLASS HOUSE FARMS'
    | 'GLASSHOUSE'
    | 'GLASSHOUSE FARMS'
    | 'GNAJA GOLD'
    | 'GRABBA LEAF'
    | 'GREEN RIVER EXTRACT'
    | 'GREEN RIVER EXTRACTS'
    | 'HALARA'
    | 'HEAVENLY SWEET'
    | 'HEMP BOMBS'
    | 'HEMP ICE'
    | 'HEMP ZONE'
    | 'HEMPARILLO'
    | 'HEMPBOMBS'
    | 'HERBAL CLEAN'
    | 'HHEMP'
    | 'HIGH GRADE'
    | 'HIGH GRADE FARMS'
    | 'HIGH GRADE FARMSG'
    | 'HIGH HEMP'
    | 'HIGH SPIRITS'
    | 'HIGH SUPPLY'
    | 'HIMALAYA'
    | 'HINEYBUTTER'
    | 'HONEY DEW'
    | 'HONEYBUTTER'
    | 'HOT SUGAR'
    | 'HOT SUGAR'
    | 'HUMBOLDT'
    | 'HUMBOLDT SEED CO'
    | 'HUMBOLDT TERP COUNCIL'
    | 'HUSH'
    | 'JAMAICAN'
    | 'JEETER'
    | 'JEETER JUICE'
    | "JEFF'S SESSIONS"
    | 'JETTY'
    | 'JUCIY JAY'
    | 'JUICY JAY'
    | "JUICY JAY'S"
    | 'JUICY JAYS'
    | 'JUST'
    | 'JUST CBD'
    | 'KEEF LIFE H20'
    | 'KHALIFA KUSH'
    | 'KING PALM'
    | 'KING PIN'
    | 'KINGROLL'
    | 'KINGS GARDEN'
    | 'KIVA'
    | 'KLARITY KRATOM'
    | 'KOA'
    | 'KRAVE'
    | 'KUSHY PUNCH'
    | 'LARAMIE'
    | 'LEVEL'
    | 'LIGHTER LEASH'
    | 'LIME'
    | 'LMFAO'
    | 'LOOKAH'
    | 'LOOKAH ORIGINAL DESIGN GLASS'
    | 'LOOKAH ORIGNAL DESIGN GLASS'
    | 'LOWELL'
    | 'LUMPYS FLOWERS'
    | 'MARY JONES'
    | 'MAS CANNABIS CO.'
    | 'MAS CANNNABIS CO.'
    | 'MEDTAINER'
    | 'MIDS FACTORY'
    | 'MIDS FCTORY'
    | 'MIDSFACTORY'
    | 'MOON'
    | 'MR. PURPLE'
    | 'MR.PURPLE'
    | 'NATURE CURATED'
    | 'NEON'
    | 'NFUZED'
    | 'NOIR'
    | 'NORTHERN EMERALD'
    | 'NORTHERN EMERALDS'
    | 'O.P.M.S'
    | 'OCB'
    | 'OH WELL'
    | 'PACIFC STONE'
    | 'PACIFIC STONE'
    | 'PACIFIC STONE-'
    | 'PANDA CORE'
    | 'PANDA DROP'
    | "PAP'S HERB"
    | 'PAPA and BARKLEY'
    | "PAPA'S HERB"
    | "PAPA'S HERBS"
    | 'PAPAS HERB'
    | 'PHAT PANDA'
    | 'PLATINUM LIME'
    | 'PLATINUM LINE'
    | 'PLUS'
    | 'POD'
    | 'POWER HOUSE'
    | 'PROTAB'
    | 'PUFF'
    | 'PUFF POP'
    | 'PURE'
    | 'PURE LYFE'
    | 'QUICKIES'
    | 'RANDY'
    | 'RAW'
    | 'RAW GARDEN'
    | 'RAW GARDEN'
    | 'RONIN'
    | 'ROYAL BLUNT'
    | 'ROYAL BLUNTS'
    | 'SAOIRSE'
    | 'SCORCH TORCH'
    | 'SCREAMING TRUMPETS'
    | 'SECRET SAUCE EXTRACTS'
    | 'SEED JUNK'
    | 'SEED JUNKY'
    | 'SELECT'
    | 'SEVEN LEAVES'
    | 'SHAMAN'
    | 'SHAMAN RESERVE'
    | 'SIKRET'
    | 'SKUNK BRAND'
    | 'SKUNK FEATHER'
    | 'SNICKELFRITZ'
    | 'SNICKLE FRITZ'
    | 'SNICKLEFRITZ'
    | 'SNIKLEFRITZ'
    | 'SPACE COYOTE'
    | 'SPARKX'
    | 'SPARX'
    | 'SPECIAL BLUE'
    | 'STATEHOUSE'
    | 'STIIIZY'
    | 'STIIZY'
    | 'TATAOO'
    | 'TECHNO'
    | 'TERP CRUSH'
    | 'TESLA'
    | 'THE PAIRIST'
    | 'TIME MACHINE'
    | 'TIMELESS'
    | 'TIMLESS'
    | 'TOKER POKER'
    | 'TOP'
    | 'TRICHOME'
    | 'TRUE HEMP'
    | 'TUTTI'
    | 'TYSON 2.0'
    | 'UNCLE ARINES'
    | "UNCLE ARNIE'S"
    | 'UNCLE ARNIES'
    | "UNCLE'S ARNIES"
    | 'UP NORTH'
    | 'VETCBD'
    | 'VIRUS GLASS'
    | 'VISTAL EXTRACTS'
    | 'WAXMAID'
    | 'WEIGHMAX'
    | 'WEST COAST TREEZ'
    | 'WHIP IT'
    | 'WILD HEMP'
    | 'WULF'
    | 'YOCAN'
    | 'YUMMI KARMA'
    | 'ZAIG ZAG'
    | 'ZEN'
    | 'ZIG ZAG'
    | 'ZIPS'
    | 'LAKE FEST CUP'
  )[];
  categories?:
    | (
        | 'beverage'
        | 'pill'
        | 'tincture'
        | 'cartridge'
        | 'preroll'
        | 'flower'
        | 'extract'
        | 'edible'
        | 'plant'
        | 'merch'
      )[]
    | null;
  image: string | Media;
  updatedAt: string;
  createdAt: string;
}
export interface User {
  id: string;
  updatedAt: string;
  createdAt: string;
  email: string;
  resetPasswordToken?: string | null;
  resetPasswordExpiration?: string | null;
  salt?: string | null;
  hash?: string | null;
  loginAttempts?: number | null;
  lockUntil?: string | null;
  password: string | null;
}
export interface PayloadPreference {
  id: string;
  user: {
    relationTo: 'users';
    value: string | User;
  };
  key?: string | null;
  value?:
    | {
        [k: string]: unknown;
      }
    | unknown[]
    | string
    | number
    | boolean
    | null;
  updatedAt: string;
  createdAt: string;
}
export interface PayloadMigration {
  id: string;
  name?: string | null;
  batch?: number | null;
  updatedAt: string;
  createdAt: string;
}


declare module 'payload' {
  export interface GeneratedTypes extends Config {}
}