import { CollectionConfig } from "payload/types";

export const Deals: CollectionConfig = {
  slug: "deals",
  fields: [
    {
      name: "active",
      type: "checkbox",
      defaultValue: true,
      label: "Active Promotion",
    },
    {
      name: "title",
      type: "text",
      required: true,
      label: "Deal Title",
    },
    {
      name: "description",
      type: "textarea",
      required: true,
      label: "Deal Description",
    },
    {
      name: "brand",
      type: "select",
      options: [
        { label: "Elyon", value: "ELYON" },
        { label: "Juicy Jay's", value: "JUICY JAY'S" },
        { label: "Raw", value: "RAW" },
        { label: "Eagle", value: "EAGLE" },
        { label: "High Hemp", value: "HIGH HEMP" },
        { label: "Dompen", value: "DOMPEN" },
        { label: "Glasshouse", value: "GLASSHOUSE" },
        { label: "Green River Extracts", value: "GREEN RIVER EXTRACTS" },
        { label: "Equilibrium Genetics", value: "EQUILIBRIUM GENETICS" },
        { label: "Stiizy", value: "STIIZY" },
        { label: "Lookah", value: "LOOKAH" },
        { label: "Everyday Slugger", value: "EVERYDAY SLUGGER" },
        { label: "Floracal", value: "FLORACAL" },
        { label: "Tyson 2.0", value: "TYSON 2.0" },
        { label: "Level", value: "LEVEL" },
        { label: "Akwaaba Farms", value: "AKWAABA FARMS" },
        { label: "Big Boy  Dro", value: "BIG BOY  DRO" },
        { label: "Uncle Arnie's", value: "UNCLE ARNIE'S" },
        { label: "Puff Pop", value: "PUFF POP" },
        { label: "Northern Emeralds", value: "NORTHERN EMERALDS" },
        { label: "Keef Life H20", value: "KEEF LIFE H20" },
        { label: "High Spirits", value: "HIGH SPIRITS" },
        { label: "Royal Blunt", value: "ROYAL BLUNT" },
        { label: "Stiiizy", value: "STIIIZY" },
        { label: "Snicklefritz", value: "SNICKLEFRITZ" },
        { label: "Juicy Jay", value: "JUICY JAY" },
        { label: "Ae El Blunto", value: "AE EL BLUNTO" },
        { label: "Everyday Dabs", value: "EVERYDAY DABS" },
        { label: "Abx", value: "ABX" },
        { label: "Waxmaid", value: "WAXMAID" },
        { label: "High Grade Farms", value: "HIGH GRADE FARMS" },
        { label: "Raw Garden", value: "RAW GARDEN" },
        { label: "Flav", value: "FLAV" },
        { label: "Herbal Clean", value: "HERBAL CLEAN" },
        { label: "Koa", value: "KOA" },
        { label: "Emerald  Bay Extracts", value: "EMERALD  BAY EXTRACTS" },
        { label: "Oh Well", value: "OH WELL" },
        { label: "King Palm", value: "KING PALM" },
        { label: "Jeeter", value: "JEETER" },
        { label: "Humboldt Terp Council", value: "HUMBOLDT TERP COUNCIL" },
        { label: "Baby Jeeter", value: "BABY JEETER" },
        { label: "Element", value: "ELEMENT" },
        { label: "Lighter Leash", value: "LIGHTER LEASH" },
        { label: "Emerlad Bay Extracts", value: "EMERLAD BAY EXTRACTS" },
        { label: "Kushy Punch", value: "KUSHY PUNCH" },
        { label: "Seven Leaves", value: "SEVEN LEAVES" },
        { label: "Ash and Ember", value: "ASH AND EMBER" },
        { label: "Lmfao", value: "LMFAO" },
        { label: "Royal Blunts", value: "ROYAL BLUNTS" },
        { label: "Clsics", value: "CLSICS" },
        { label: "Bemore", value: "BEMORE" },
        { label: "Bolt", value: "BOLT" },
        { label: "Toker Poker", value: "TOKER POKER" },
        { label: "Klarity Kratom", value: "KLARITY KRATOM" },
        { label: "Pacific Stone", value: "PACIFIC STONE" },
        { label: "Vetcbd", value: "VETCBD" },
        { label: "Skunk Brand", value: "SKUNK BRAND" },
        { label: "Techno", value: "TECHNO" },
        { label: "Gelato", value: "GELATO" },
        { label: "Shaman", value: "SHAMAN" },
        { label: "Drops", value: "DROPS" },
        { label: "Nfuzed", value: "NFUZED" },
        { label: "Puff", value: "PUFF" },
        { label: "Eighty East", value: "EIGHTY EAST" },
        { label: "Panda Core", value: "PANDA CORE" },
        { label: "Zig Zag", value: "ZIG ZAG" },
        { label: "Emerald Sky", value: "EMERALD SKY" },
        { label: "Kiva", value: "KIVA" },
        { label: "Krave", value: "KRAVE" },
        { label: "Clipper", value: "CLIPPER" },
        { label: "Camino", value: "CAMINO" },
        { label: "Bangers", value: "BANGERS" },
        { label: "Cannatrust", value: "CANNATRUST" },
        { label: "Pure Lyfe", value: "PURE LYFE" },
        { label: "Plus", value: "PLUS" },
        { label: "Mids Factory", value: "MIDS FACTORY" },
        { label: "Artisanal Hemp", value: "ARTISANAL HEMP" },
        { label: "West Coast Treez", value: "WEST COAST TREEZ" },
        { label: "Emerald Bay Extracts", value: "EMERALD BAY EXTRACTS" },
        { label: "Flawless Flowers", value: "FLAWLESS FLOWERS" },
        { label: "B.O.B Stash", value: "B.O.B STASH" },
        { label: "Yummi Karma", value: "YUMMI KARMA" },
        { label: "Zaig Zag", value: "ZAIG ZAG" },
        { label: "Hemp Zone", value: "HEMP ZONE" },
        { label: "Elements", value: "ELEMENTS" },
        { label: "Yocan", value: "YOCAN" },
        { label: "Shaman Reserve", value: "SHAMAN RESERVE" },
        { label: "Big Pete's", value: "BIG PETE'S" },
        { label: "Gealto", value: "GEALTO" },
        { label: "Whip It", value: "WHIP IT" },
        { label: "Papa's Herb", value: "PAPA'S HERB" },
        { label: "Generic...", value: "GENERIC..." },
        { label: "Pure", value: "PURE" },
        { label: "Honeybutter", value: "HONEYBUTTER" },
        { label: "High Supply", value: "HIGH SUPPLY" },
        { label: "Care By Design", value: "CARE BY DESIGN" },
        { label: "Baliey's", value: "BALIEY'S" },
        { label: "Mary Jones", value: "MARY JONES" },
        { label: "Glass House Farms", value: "GLASS HOUSE FARMS" },
        { label: "Big Boy Dro", value: "BIG BOY DRO" },
        { label: "Wulf", value: "WULF" },
        { label: "Juicy Jays", value: "JUICY JAYS" },
        { label: "O.P.M.S", value: "O.P.M.S" },
        { label: "Midsfactory", value: "MIDSFACTORY" },
      ],
    },
    {
      name: "categories",
      type: "select",
      hasMany: true,
      options: [
        { label: "Beverage", value: "beverage" },
        { label: "Pill", value: "pill" },
        { label: "Tincture", value: "tincture" },
        { label: "Cartridge", value: "cartridge" },
        { label: "Preroll", value: "preroll" },
        { label: "Flower", value: "flower" },
        { label: "Extract", value: "extract" },
        { label: "Edible", value: "edible" },
        { label: "Plant", value: "plant" },
        { label: "Merch", value: "merch" },
      ],
    },
    {
      name: "image",
      type: "upload",
      relationTo: "media",
      required: true,
      label: "Deal Image",
    },
  ],
};
