name: lint & typecheck

on: [push]

jobs:
  lint-and-typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup bun
        uses: oven-sh/setup-bun@v2
        with:
          bun-version: 1.3.1

      - name: install dependencies
        run: bun install --frozen-lockfile

      # this is a workaround for https://github.com/vercel/next.js/issues/53959
      - name: create next-env.d.ts
        run: echo -e '/// <reference types="next" />\n/// <reference types="next/image-types/global" />' > ./next-env.d.ts

      - name: run lint
        run: NEXT_TELEMETRY_DISABLED=1 bun run lint

      - name: run typecheck
        run: bun run typecheck
