name: lint & typecheck

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: intall dependencies
        run: npm ci

      - name: run lint
        run: NEXT_TELEMETRY_DISABLED=1 npm run lint

  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: checkout repo
        uses: actions/checkout@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: install dependencies
        run: npm ci

      # this is a workaround for https://github.com/vercel/next.js/issues/53959
      - name: create next-env.d.ts
        run: echo -e '/// <reference types="next" />\n/// <reference types="next/image-types/global" />' > ./next-env.d.ts

      - name: run typecheck
        run: npm run typecheck
